config/routes.rb
Cms::Application.routes.draw do
  
  resources :gift_certs

  resources :phones

  resources :addresses

  resources :owners
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :owners do
    resources :businesses
  end

  resources :businesses do
    resources :customers
    resources :services
    resources :packages
  end

  resources :customers do
    resources :visits
  end

  root to: 'static_pages#home'

  get '/signup',      to: 'owners#new'
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/signin',      to: 'sessions#new'

  post '/signin',     to: 'sessions#create'

  delete '/signout',  to: 'sessions#destroy'
  
  








end

app/models/service.rb

class Service < ActiveRecord::Base

	# a service may belong to one business through business_id
  belongs_to :business

  has_many :services_visits
  has_many :visits, through: :services_visits
  has_many :services_packages
  has_many :packages, through: :services_packages
  has_many :prices, as: :cost
  accepts_nested_attributes_for :prices

  validates :business_id, presence: true
  validates_presence_of :name
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :get_business_and_owner
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def index
    @services = @business.services
  end

  def show
  end

  def new
    @service = @business.services.build
    @service.prices.build(params[:price])
  end

  def edit
    @service.prices ||= @service.prices.build(params[:price])
  end
  
  def create
    @service = @business.services.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to business_services_url(@business), notice: 'Service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to business_services_url(@business), notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to business_services_url(@business) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :business_id, :prices_attributes => [:id, :amount])
    end

    def get_business_and_owner
      @business = Business.find(params[:business_id])
      @owner = @business.owner      
    end
end

app/views/services/_form.html.erb
<%= form_for([@business, @service]) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div>
  <%= f.fields_for :prices do |price| %>
    <%= render partial: 'prices/form', locals: { f: price } %>
  <% end %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service <%= @service.name %> for <%= @business.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', [@business, @service] %> |
<%= link_to 'Back', business_services_path(@business) %>

app/views/services/index.html.erb
<h1>Listing services for <%= link_to @business.name %></h1>

<% if @business.services.count > 0 %>
<table class="table table-hover table-condensed">
  <tr>
    <th>Service name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
  </tr>

<% @services.each do |service| %>
  <tr>
    <td><%= link_to service.name, [@business, service] %></td>
    <td><%= service.description %></td>
    <td><% service.prices.each do |p| %>
        <%= number_to_currency(p.amount) %>
    <% end %>
    </td>
    <td><%= link_to 'Edit', edit_business_service_path(@business, service), class: 'btn' %></td>
    <td><%= link_to 'Delete', [@business, service], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<% else %>
  <p><%= @business.name %> has not added any business services.   Please do so now.</p>
<% end %>

<p>
  <%= link_to 'New Service', new_business_service_path(@business) %> |
  <%= link_to 'Back', owner_businesses_path(@owner) %>
</p>

app/views/services/new.html.erb
<h1>New service for <%= link_to @business.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', business_services_path(@business) %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Service name:</b>
  <%= @service.name %>
</p>

<p>
  <b>Description:</b>
  <%= @service.description %>
</p>

<p>
  <b>Price:</b>
	<% @service.prices.each do |p| %>
	  <%= number_to_currency(p.amount) %>
	<% end %>
</p>

<%= link_to 'Edit', edit_business_service_path(@business, @service) %> |
<%= link_to 'Back', business_services_path(@business) %>