config/routes.rb
Cms::Application.routes.draw do
  
  resources :gift_certs

  resources :phones

  resources :addresses

  resources :owners
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :owners do
    resources :businesses
  end

  resources :businesses do
    resources :customers
    resources :services
    resources :packages
  end

  resources :customers do
    resources :visits
  end

  root to: 'static_pages#home'

  get '/signup',      to: 'owners#new'
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/signin',      to: 'sessions#new'

  post '/signin',     to: 'sessions#create'

  delete '/signout',  to: 'sessions#destroy'
  
  








end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :get_owner
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  #helper_method :sort_column, :sort_direction


  def index
    @businesses = @owner.businesses
  end

  def show
    #@customer = @business.customers.order(sort_column + " " + sort_direction)
  end

  def new
    @owner = Owner.find(params[:owner_id])
    @business = @owner.businesses.build
    @business.build_address(params[:address])
  end

  def edit
    @business.address ||= @business.build_address(params[:address])
  end

  def create
    @business = @owner.businesses.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to owner_businesses_url(@owner), notice: 'Business was successfully created.' }
        format.json { render action: 'show', status: :created, location: @business }
      else
        format.html { render action: 'new' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
   #@business.address.update(params[:address])
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to owner_businesses_url(@owner), notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to owner_businesses_url(@owner) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = @owner.businesses.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :description, :address_attributes => [:id, :line1, :line2, :city, :state, :zip])
    end

    def get_owner
      @owner = Owner.find(params[:owner_id])
    end

    #def sort_column
    #  Customer.column_names.include?(params[:sort]) ? params[:sort] : "first_name"    
    #end

    #def sort_direction
    #  %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    #end
end

app/views/businesses/_form.html.erb
<%= form_for([@owner, @business]) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <%= f.fields_for :address do |address| %>
    <%= render partial: 'addresses/form', locals: { f: address } %>
  <% end %>

 
    <%= f.submit class: "btn btn-primary" %>
 
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Listing businesses for <%= link_to @owner.name %></h1>

<table>
  <thead>
    <tr>
      <th>Business</th>
      <th>Description</th>
      <th>Services</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
    <tr>
      <td><%= link_to business.name, [@owner, business] %></td>
      <td><%= business.description %></td>
      <td><%= business.services.count %></td>
      <td><%= link_to 'Edit', edit_owner_business_path(@owner, business) %></td>
      <td><%= link_to 'Destroy', [@owner, business], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Business', new_owner_business_path(@owner) %>

app/views/businesses/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<h1>New business</h1>

			<%= render 'form' %>

			<%= link_to 'Back', owner_businesses_path(@owner) %>
		</div>
	</div>
</div>

app/views/businesses/show.html.erb
<div class="row">
  <div class="col-lg-3 col-lg-offset-1 sidebar">
    <div class="panel panel-primary">
      <div class="panel-heading"> 
        <h3 class="panel-title">Owner and Business Info</h3>
      </div>
      <div class="panel-body">
        <p>
          Hello <%= link_to current_owner.first_name, current_owner %>
          Above link a profile link.
          Business Name: <%= @business.name %>
        </p>
      </div>
    </div>


      <% if @business.services.count < 1 %>
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Business Services</h3>
          </div>
          <div class="panel-body">
            <p>
              To get started you need to enter business services.
              <%= link_to "Please click here to do so.", business_services_url(@business) %>
            </p>
          </div>
        </div>
      <% else %>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Business Services</h3>
          </div>
          <div class="panel body">
          <p>
            Total business services: <%= link_to @business.services.count, business_services_path(@business) %>
            Add top five business services here later:
          </p>
          </div>
        </div>
      <% end %>
 

<div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Business Information</h3>
      </div>
      <div class="panel body">
        <p>Customer count: <%= link_to @business.customers.count, business_customers_url(@business) %></p>
        <p><%= link_to "Click here to add a customer.", new_business_customer_path(@business) %></p>
        <p>
          Special packages: 
          <% if @business.packages.count < 1 %>
            If you have special package pricing, <%= link_to "please click here to create", business_packages_url(@business) %>
        </p>
          <% else %>
          <p>Special package count: <%= link_to @business.packages.count, business_packages_path(@business) %></p>
          <% end %>
      </div>
    </div>
  </div>

  <div class="col-lg-7">
    <h3> Customer List for <%= @business.name %></h3>
      <table class="table table-condensed table-striped table-bordered" id="customers">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Visits</th>
            <th>Last Visit</th>
            <th>Package owner</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @business.customers.each do |customer| %>
          <tr>
            <td><%= link_to customer.first_name, [@business, customer] %></td>
            <td><%= customer.last_name %></td>
            <td><%= customer.email %></td>
            <td><% customer.phones.each do |phone| %>
              <%= number_to_phone(phone.number, area_code: true) %><br />
            <% end %></td>
            <td><%= link_to customer.visits.count, customer_visits_path(customer) %></td>
    <td><%= customer.visits.count == 0 ? "No visits" : customer.visits.last.        date_of_visit %></td>
            <td><%= customer.packages.count == 0 ? "No" : "Yes" %></td>
            <td><%= link_to 'Edit', edit_business_customer_path(@business, customer), class: 'btn' %></td>
            <td><%= link_to 'Delete', [@business, customer], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          </tr>
          <% end %>
        </tbody>
        </table>   
      </div>
    </div> 

    <div class="row">
      <div class="col-md-6 col-md-offset-1">
        <%= link_to 'Edit', edit_owner_business_path(@owner, @business) %> |
        <%= link_to 'Back', owner_businesses_path(@owner) %>
      </div>
    </div>
