config/routes.rb
Cms::Application.routes.draw do
  
  resources :gift_certs

  resources :phones

  resources :addresses

  resources :owners
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :owners do
    resources :businesses
  end

  resources :businesses do
    resources :customers
    resources :services
    resources :packages
  end

  resources :customers do
    resources :visits
  end

  root to: 'static_pages#home'

  get '/signup',      to: 'owners#new'
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/signin',      to: 'sessions#new'

  post '/signin',     to: 'sessions#create'

  delete '/signout',  to: 'sessions#destroy'
  
  








end

app/models/owner.rb
# == Schema Information
#
# Table name: owners
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#  middle_name     :string(255)
#

class Owner < ActiveRecord::Base

  has_secure_password	
  before_save { |owner| owner.email = email.downcase }
  before_save :create_remember_token

  has_many :businesses

  has_one :address, as: :addressable
  accepts_nested_attributes_for :address

  
  validates :first_name, :last_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  #simple interpolation with first and last name to a string on a name call.
  def name
    "#{first_name} #{last_name}".to_s   
  end  

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_owner,  only: [:show, :edit, :update, :destroy]
  before_action :correct_owner,    only: [:show, :edit, :update, :destroy]



  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
    @owner.build_address(params[:address])
  end

  # GET /owners/1/edit
  def edit
    @owner.address ||= @owner.build_address(params[:address])
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        sign_in @owner
        format.html { redirect_to root_path, notice: 'Owner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @owner }
      else
        format.html { render action: 'new' }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :middle_name, :email, :password, :password_confirmation, :address_attributes => [:id, :line1, :line2, :city, :state, :zip])
    end

    def signed_in_owner
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."  
      end   
    end

    def correct_owner
      redirect_to(root_path) unless current_owner?(@owner)      
    end
end

app/views/owners/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@owner) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :middle_name %>
    <%= f.text_field :middle_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
 
    <%= f.label :email %>
    <%= f.email_field :email %>
 
    <%= f.label :password %>
    <%= f.password_field :password %>
 
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <p>Please provide an address for you.  We'll get your business address later in the process:</p>

    <%= f.fields_for :address do |address| %>
      <%= render partial: 'addresses/form', locals: { f: address } %>
    <% end %>

    <%= f.submit class: 'btn btn-lg btn-primary' %>
  </div>
  <% end %>
</div>


app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
    <tr>
      <td><%= owner.first_name %></td>
      <td><%= owner.last_name %></td>
      <td><%= owner.email %></td>
      <td><%= owner.password_digest %></td>
      <td><%= link_to 'Show', owner %></td>
      <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
      <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<% provide(:title, "#{@owner.name} Profile Page") %>
<div class="container">
	<div class="row">
	<div class="col-md-6">
		<p>
			<strong>Owner Name:</strong>
			<%= link_to @owner.name, edit_owner_path(@owner) %>
		</p>
		<p>
  		<strong>Email:</strong>
  		<%= @owner.email %>
		</p>

		<%= link_to 'Edit', edit_owner_path(@owner) %>
	</div>

	<div class="col-md-6">
		<% if @owner.businesses.count == 0 %>
			<p>In order to manage your customers you need to tell us about your business.</p>
			<p>Please <%= link_to "add your business here.", new_owner_business_path(@owner) %></p>
	  <% else %>
	    <% @owner.businesses.each do |business| %>
	      <p>This page is mostly just a placeholder for more.   We'll probably have it be a dashboard of lots of cool stuff about each registered business.   Things like how many customers, how much has been spent, biggest spender, number of visits, etc.   For now, just click the manage your business link below to start adding customers.</p>
	      <%= link_to "Manage #{business.name}", owner_business_path(@owner, business) %>
	    <% end %>
	 	<% end %>
	</div>
	</div>
</div>