config/routes.rb
Cms::Application.routes.draw do
  
  resources :gift_certs

  resources :phones

  resources :addresses

  resources :owners
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :owners do
    resources :businesses
  end

  resources :businesses do
    resources :customers
    resources :services
    resources :packages
  end

  resources :customers do
    resources :visits
  end

  root to: 'static_pages#home'

  get '/signup',      to: 'owners#new'
  get '/help',        to: 'static_pages#help'
  get '/about',       to: 'static_pages#about'
  get '/signin',      to: 'sessions#new'

  post '/signin',     to: 'sessions#create'

  delete '/signout',  to: 'sessions#destroy'
  
  








end

app/helpers/layout_helper.rb
module LayoutHelper
def copyright_notice_year_range(start_year)
	start_year = start_year.to_i

	current_year = Time.new.year

	if current_year > start_year && start_year > 2000
		"#{start_year} - #{current_year}"
	elsif start_year > 2000
		"#{start_year}"
	else
		"#{current_year}"
	end
end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="row">
	  <div class="col-md-4 col-md-offset-1"
  <small>
    &copy; <%= copyright_notice_year_range(2009) %> <%= link_to "Hamco Internet Solutions", "http://hamcois.com" %>
  </small>
  </div>
</footer>

app/views/layouts/_header.html.erb
    <header>
      <div class="navbar navbar-fixed-top navbar-default navbar-inverse">
        <div class="row">
          <div class="col-md-1 col-md-offset-1">
            <div class="navbar-header">
              <%= link_to "CMS", '#', class: "navbar-brand" %>
           </div>
          </div>
          <div class="col-md-4 col-md-push-5" <div>
            <div class="navbar-collapse collapse", role="navigation">
 
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Help",    help_path %></li>
              <li><%= link_to "About",   about_path %></li>
              <li><%= link_to "Contact", '#' %></li>
            <% if signed_in? %>
              <li><%= link_to "Businesses", owner_businesses_path(@owner) %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 Account <b class="caret"></b>
                </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_owner %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
              </ul>
            </li>
           <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
             </ul>
            </div>
            </div>
          </div>
       </div>
    </header>
 

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header' %>

    <%= render 'layouts/messages' %>

    <%= yield %>
              
    <%= render 'layouts/footer' %>
   
    <div class="container">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>